src/Entity/OrderUser.php
<?php


namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\OrderRepository;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 */
class OrderUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $firstName;

    public function getFirstName(): string
    {
        return (string) $this->firstName;
    }

    public function setFirstName(String $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $lastName;

    public function getLastName(): string
    {
        return (string) $this->lastName;
    }

    public function setLastName(String $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $address;

    public function getAddress(): string
    {
        return (string) $this->address;
    }

    public function setAddress(String $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $country;

    public function setCountry(String $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=ShopList::class, mappedBy="orderId", cascade={"persist"})
     */
    private $shopLists;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priceOf;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $subtotalOf;

    public function __construct()
    {
        $this->shopLists = new ArrayCollection();
    }

    public function getCountry(): string
    {
        return (string) $this->country;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|ShopList[]
     */
    public function getShopLists(): Collection
    {
        return $this->shopLists;
    }

    public function addShopList(ShopList $shopList): self
    {
        if (!$this->shopLists->contains($shopList)) {
            $this->shopLists[] = $shopList;
            $shopList->setOrderId($this);
        }

        return $this;
    }


    public function removeShopList(ShopList $shopList): self
    {
        if ($this->shopLists->contains($shopList)) {
            $this->shopLists->removeElement($shopList);
            // set the owning side to null (unless already changed)
            if ($shopList->getOrderId() === $this) {
                $shopList->setOrderId(null);
            }
        }

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZip(): ?int
    {
        return $this->zipCode;
    }

    public function setZip(int $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phone): self
    {
        $this->phoneNumber = $phone;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->priceOf;
    }

    public function setPrice(int $priceOf): self
    {
        $this->priceOf = $priceOf;

        return $this;
    }

    public function getSubtotal(): ?int
    {
        return $this->subtotalOf;
    }

    public function setSubtotal(int $subtotalOf): self
    {
        $this->subtotalOf = $subtotalOf;

        return $this;
    }

}

src/Controller/ShippingController.php
<?php

namespace App\Controller;

use App\Entity\OrderUser;
use App\Entity\Product;
use App\Entity\ShopList;
use App\Entity\User;
use App\Repository\ProductRepository;
use OrderType;
use PhpParser\Node\Expr\List_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use UserType;

class ShippingController extends AbstractController
{


    private ProductRepository $productRepository;

    public function __construct(ProductRepository $productRepository)
    {
        $this->productRepository = $productRepository;
    }

    private $array;

    /**
     * @Route("/shipping", name="order")
     * @param \Symfony\Component\HttpFoundation\Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createOrder(Request $request)
    {

//        $array = array(
//            '1' => 1,
//            '4' => 2,
//            '5' => 3
//        );
//
//
//        $em = $this->getDoctrine()->getManager();
//        $json = json_encode($array);
//        $array = json_decode("localStorage.getItem('cart')");
//if($_POST['param']) {
//    $array = json_decode($_POST['param']);
//    exit();
//} else{
//    $array = array();
//}
//
//        $array = json_decode($json);

//        if ($_POST['search']) {
//            $json = $_POST['search'];
//            $array = json_decode($json);
//        } else {
//            $array =array();
//        }
//        dd($array);

        $order = new OrderUser();
        $user = $this->getUser();

        $products = array();
        $price = 0;
        $taxes = 13;
        $this->getJson();
        foreach ($this->array as $k => $v) {
            $product = $this->productRepository->find($k);
            $shopList = new ShopList();
            $shopList->setProduct($product);
            $shopList->setCount($v);
            $shopList->setOrderId($order);
            $price = $price + $product->getCost() * $v;\
            array_push($products, $shopList);
        }
        $order->setPrice($price);
        $subtotal = $price + $taxes;
        $order->setSubtotal($subtotal);


        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);
//            dd($order);
        if ($form->isSubmitted()) {

            $order = $form->getData();
            $order->setUser($user);
            $em = $this->getDoctrine()->getManager();
            $em->persist($order);
            $em->flush();
//            dd($order);
            foreach ($this->array as $k => $v) {
                $product = $this->productRepository->find($k);
                $shopList = new ShopList();
                $shopList->setProduct($product);
                $shopList->setCount($v);
                $shopList->setOrderId($order);
                $em->persist($shopList);
            }

            $em->flush();
            return $this->redirect("profile");
        }

        return $this->render('shipping/index.html.twig', [
            'form' => $form->createView(),
            'products' => $products,
            'subtotal' => $price,
            'total' => $subtotal,
            'taxes' => $taxes
        ]);
    }

    function getJson()
    {
        if ($_POST['search']) {
            $json = $_POST['search'];
            $array = json_decode($json);
        } else {
            $array = array();
        }
        $this->array = $array;
    }
}

templates/shipping/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ShippingController!{% endblock %}

{% block body %}
    <style>
        .navbar-item {
            margin-right: 10px;
            margin-left: 10px;
        }
    </style>
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top border" style="box-shadow: black">
        <div class="container-fluid">
            <a href="/" class="navbar-brad"><img
                        src="https://sun7-6.userapi.com/2JYupaQXK7tuU6qqEN3Y3W0C568RoyyJq1Pu6g/8gOYGcN_NqE.jpg"> MERCHEAP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="navbar-item">
                        <a href="/profile" class="nav-link">Profile</a>
                    </li>
                    <li class="navbar-item">
                        <a href="/goods" class="nav-link">Shop</a>
                    </li>
{#                    <li class="navbar-item active">#}
{#                        <a href="/login" class="nav-link">Login</a>#}
{#                    </li>#}
                    <li class="navbar-item">
                        <a href="/logout" class="nav-link">Logout</a>
                    </li>
                </ul>
                <div class="navbar-item">
                    <form action="/cart" method="post">
                            <textarea type="text" name="search" value="" hidden>
                            </textarea>
                        <button class="btn-dark">
                            <i class="fas fa-shopping-cart"></i>
                            Your Cart
                        </button>
                    </form>
                </div>

            </div>

        </div>
    </nav>



    </br>
    <div class="container">
        <div class="row">
            <!-- Первый блок -->
            <div class="col-8" style="height: 200px;">
                <h2>
                    <small class="text-secondary">Shipping detail</small>
                </h2>
                <hr/>
                {{ form_start(form) }}
                <div class="row">
                </br>
                    {{ form_widget(form.first_name, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "First Name"}}, {'id': 'firstName' }) }}

                     {{ form_widget(form.last_name, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "Last Name"}}, {'id': 'lastName' }) }}
                </div>
                </br>

                {{ form_widget(form.address, {'attr': {'class': "form-control col-10", 'onblur': "f()", 'placeholder': "Address"}}, {'id': 'address' }) }}
                </br>
                <div class="row">

                    {{ form_widget(form.country, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "Country"}}, {'id': 'country' }) }}

                    {{ form_widget(form.city, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "City"}}, {'id': 'city' }) }}
                </div>
                </br>
                <div class="row">



                    {{ form_widget(form.zip, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "Zip/Postal Code"}}, {'id': 'code' }) }}



                    {{ form_widget(form.phone_number, {'attr': {'class': "form-control col-5 mr-4 ml-3", 'onblur': "f()", 'placeholder': "Phone Number"}}, {'id': 'phoneNumber' }) }}
                </div>
                <hr color="black"/>
                <div class="row">
                    <textarea type="text" name="search" value="" hidden></textarea>
                    <button type="submit" class="col-3 mr-4 ml-3 btn btn-secondary" id="next" disabled>Next</button>
                    <button type="button" class="col-3 mr-4 ml-3 btn btn-light" id="btn_modal_window">Cancel</button>
                    <div id="error" class="error" style="color: red"></div>
                </div>
                {{ form_end(form) }}
                <div id="my_modal" class="modal">
                    <div class="modal_content">
                        <span class="close_modal_window">×</span>
                        <p>Are you sure you want to cancel the order?</p>
                        <a type="button" href="/cart" class="col-3 btn btn-light">Cancel</a>
                    </div>
                </div>
            </div>

            <!-- Второй блок -->
            <div class="col-4" style="height: 200px;">
                <h2>
                    <small class="text-secondary">Summary</small>
                </h2>
                <hr/>
                <div class="container">
                    {% if products!= null %}
                    {% for product in products %}
                    <div class="alert alert-dismissible"  onmouseover="this.style.borderColor = 'black'" onmouseout="this.style.borderColor = ''">

                        <div class="row">
{#                            <img src="https://onerepublic.com/wp-content/uploads/2019/11/1R_RM_HATSIDE_MOCK.jpg" style="wight: 90px; height: 80px">#}
                            <img src="uploads/{{ product.product.photo }}" style="wight: 90px; height: 80px">
                        </div>
                        <div class="row">
                            <h4 class="ml-3" id="productName1">
                                {{ product.product.name }}
                                </h4>
                                </br>
                                    <h5 id="price1">{{ product.product.cost }}$</h5>
                            </br>
                                    <h6 id="count1">Product count - {{ product.count }}</h6>
                            </br>
                    </div>
                    </div>
                        {% endfor %}
                    {% endif %}
                    <hr/>
                    <div class="row">
                        <div class="col-9">SUBTOTAL</div>
                        <div class="col-2" id="subtotal">${{ subtotal }}</div>
                    </div>
                    <div class="row">
                        <div class="col-9">TAXES</div>
                        <div class="col-2" id="taxes">${{ taxes }}</div>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <h3 class="col-9">
                        <small>TOTAL</small>
                    </h3>
                    <h3 class="col-2" id="total">
                        <small>${{ total }}</small>
                    </h3>
                </div>
            </div>
        </div>
    </div>

    <style>
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 135%;
            overflow: auto;
            background-color: rgba(0,0,0,0.6);
            z-index: 1000;
        }
        .modal .modal_content {
            background-color: #fefefe;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 20%;
            height: 15%;
            z-index: 99999;
        }
        .modal .modal_content .close_modal_window {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
            cursor: pointer;
        }
    </style>

    <script>
        var search = localStorage.getItem('cart');
        $("textarea[type=text]").val(search);
    </script>
    <script>
        var modal = document.getElementById("my_modal");
        var btn = document.getElementById("btn_modal_window");
        var span = document.getElementsByClassName("close_modal_window")[0];


        btn.onclick = function () {
            modal.style.display = "block";
        }

        span.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        }
    </script>
    <script>
        function f() {
            var rePhone = /^[0-9]+$/i;
            var reName = /^[A-Za-z\s]+$/i;
            var reAddress = /^[a-zA-Z0-9]+$/;

            var myPhone = document.getElementById('order_phone_number').value;
            var myFirstName = document.getElementById('order_first_name').value;
            var myLastName = document.getElementById('order_last_name').value;
            var myAddress = document.getElementById('order_address').value;
            var myCity = document.getElementById('order_city').value;
            var myCode = document.getElementById('order_zip').value;
            var myCountry = document.getElementById('order_country').value;
            var validFirstName = reName.test(myFirstName);
            var validLastName = reName.test(myLastName);
            var validPhone = rePhone.test(myPhone);
            var validCity = reName.test(myCity);
            var validAddress = reAddress.test(myAddress);
            var validCountry = reName.test(myCountry);
            var validCode = rePhone.test(myCode);
            var next = document.getElementById('next');
            if (validPhone & validFirstName & validLastName & validCode & validCity & validAddress) {
                error.innerHTML = '';
                next.disabled = false;
            }
            else if(!validFirstName){
                error.innerHTML = 'You are using invalid characters for FirstName or empty field value.'
            }
            else if (!validLastName){
                error.innerHTML = 'You are using invalid characters for LastName or empty field value.'
            }
            else if (!validAddress){
                error.innerHTML = 'You are using invalid characters for Address or empty field value.';
            }else if (myCountry === null || myCountry === 'Country'){
                error.innerHTML = 'Empty field value on country.'
            }
            else if (!validCity){
                error.innerHTML = 'You are using invalid characters for City or empty field value.';
            }
            else if (!validCode){
                error.innerHTML = 'You are using invalid characters for Zip/Portal Code or empty field value.';
            }
            else if(!validPhone){
                error.innerHTML = 'You are using invalid characters for a phone number. Example: 891273627745';

            }
        }
    </script>
    <script>
        function nullStorage() {
            var storage = localStorage.getItem('cart');
            storage.clear();
        }
    </script>
{% endblock %}